plugin:
    has_options: false
    tools:
        -
            name: agenda
            is_displayable_in_workspace: true
            is_displayable_in_desktop: true
            class: calendar
    widgets:
        -
            name: agenda
            is_configurable: false
